window.esdocSearchIndex = [
  [
    "truffle-debugger/lib/controller/actions/index.js~advance",
    "variable/index.html#static-variable-ADVANCE",
    "<span>ADVANCE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~begin_step",
    "variable/index.html#static-variable-BEGIN_STEP",
    "<span>BEGIN_STEP</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~call",
    "variable/index.html#static-variable-CALL",
    "<span>CALL</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~create",
    "variable/index.html#static-variable-CREATE",
    "<span>CREATE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/context/context.js~context",
    "class/lib/context/context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">truffle-debugger/lib/context/context.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/context/set.js~contextset",
    "class/lib/context/set.js~ContextSet.html",
    "<span>ContextSet</span> <span class=\"search-result-import-path\">truffle-debugger/lib/context/set.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/types/contract.js~contract",
    "class/lib/types/contract.js~Contract.html",
    "<span>Contract</span> <span class=\"search-result-import-path\">truffle-debugger/lib/types/contract.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/debugger.js~debugger",
    "class/lib/debugger.js~Debugger.html",
    "<span>Debugger</span> <span class=\"search-result-import-path\">truffle-debugger/lib/debugger.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~end_of_trace",
    "variable/index.html#static-variable-END_OF_TRACE",
    "<span>END_OF_TRACE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~interrupt",
    "variable/index.html#static-variable-INTERRUPT",
    "<span>INTERRUPT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~jump",
    "variable/index.html#static-variable-JUMP",
    "<span>JUMP</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~next",
    "variable/index.html#static-variable-NEXT",
    "<span>NEXT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~return",
    "variable/index.html#static-variable-RETURN",
    "<span>RETURN</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_into",
    "variable/index.html#static-variable-STEP_INTO",
    "<span>STEP_INTO</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_next",
    "variable/index.html#static-variable-STEP_NEXT",
    "<span>STEP_NEXT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_out",
    "variable/index.html#static-variable-STEP_OUT",
    "<span>STEP_OUT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_over",
    "variable/index.html#static-variable-STEP_OVER",
    "<span>STEP_OVER</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session.js~session",
    "class/lib/session.js~Session.html",
    "<span>Session</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tick",
    "variable/index.html#static-variable-TICK",
    "<span>TICK</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tock",
    "variable/index.html#static-variable-TOCK",
    "<span>TOCK</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/index.js~web3adapter",
    "class/lib/web3/index.js~Web3Adapter.html",
    "<span>Web3Adapter</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/index.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~advance",
    "function/index.html#static-function-advance",
    "<span>advance</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~beginstep",
    "function/index.html#static-function-beginStep",
    "<span>beginStep</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~call",
    "function/index.html#static-function-call",
    "<span>call</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/reducers.js~callstack",
    "function/index.html#static-function-callstack",
    "<span>callstack</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas.js~callstacksaga",
    "function/index.html#static-function-callstackSaga",
    "<span>callstackSaga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~endtrace",
    "function/index.html#static-function-endTrace",
    "<span>endTrace</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/reducers.js~functiondepth",
    "function/index.html#static-function-functionDepth",
    "<span>functionDepth</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/reducers.js~index",
    "function/index.html#static-function-index",
    "<span>index</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~interrupt",
    "function/index.html#static-function-interrupt",
    "<span>interrupt</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~jump",
    "function/index.html#static-function-jump",
    "<span>jump</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~next",
    "function/index.html#static-function-next",
    "<span>next</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/sagas.js~next",
    "function/index.html#static-function-next",
    "<span>next</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/reducers.js~reduce",
    "function/index.html#static-function-reduce",
    "<span>reduce</span> <span class=\"search-result-import-path\">truffle-debugger/lib/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~returncall",
    "function/index.html#static-function-returnCall",
    "<span>returnCall</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/sagas.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/sagas.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/sagas.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/sagas.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/sagas.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/context/selectors.js~selector",
    "variable/index.html#static-variable-selector",
    "<span>selector</span> <span class=\"search-result-import-path\">truffle-debugger/lib/context/selectors.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/selectors.js~selector",
    "variable/index.html#static-variable-selector",
    "<span>selector</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/selectors.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/selectors.js~selector",
    "variable/index.html#static-variable-selector",
    "<span>selector</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/selectors.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/selectors.js~selector",
    "variable/index.html#static-variable-selector",
    "<span>selector</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/selectors.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepinto",
    "function/index.html#static-function-stepInto",
    "<span>stepInto</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepnext",
    "function/index.html#static-function-stepNext",
    "<span>stepNext</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepout",
    "function/index.html#static-function-stepOut",
    "<span>stepOut</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepover",
    "function/index.html#static-function-stepOver",
    "<span>stepOver</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tick",
    "function/index.html#static-function-tick",
    "<span>tick</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tock",
    "function/index.html#static-function-tock",
    "<span>tock</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/effects.js~view",
    "function/index.html#static-function-view",
    "<span>view</span> <span class=\"search-result-import-path\">truffle-debugger/lib/effects.js</span>",
    "function"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/context/context.js",
    "file/lib/context/context.js.html",
    "lib/context/context.js",
    "file"
  ],
  [
    "lib/context/context.js~context#addresses",
    "class/lib/context/context.js~Context.html#instance-member-addresses",
    "lib/context/context.js~Context#addresses",
    "member"
  ],
  [
    "lib/context/context.js~context#binary",
    "class/lib/context/context.js~Context.html#instance-member-binary",
    "lib/context/context.js~Context#binary",
    "member"
  ],
  [
    "lib/context/context.js~context#constructor",
    "class/lib/context/context.js~Context.html#instance-constructor-constructor",
    "lib/context/context.js~Context#constructor",
    "method"
  ],
  [
    "lib/context/context.js~context#contractname",
    "class/lib/context/context.js~Context.html#instance-member-contractName",
    "lib/context/context.js~Context#contractName",
    "member"
  ],
  [
    "lib/context/context.js~context#instructionatprogramcounter",
    "class/lib/context/context.js~Context.html#instance-method-instructionAtProgramCounter",
    "lib/context/context.js~Context#instructionAtProgramCounter",
    "method"
  ],
  [
    "lib/context/context.js~context#instructions",
    "class/lib/context/context.js~Context.html#instance-member-instructions",
    "lib/context/context.js~Context#instructions",
    "member"
  ],
  [
    "lib/context/context.js~context#merge",
    "class/lib/context/context.js~Context.html#instance-method-merge",
    "lib/context/context.js~Context#merge",
    "method"
  ],
  [
    "lib/context/context.js~context#programcountermapping",
    "class/lib/context/context.js~Context.html#instance-member-programCounterMapping",
    "lib/context/context.js~Context#programCounterMapping",
    "member"
  ],
  [
    "lib/context/context.js~context#source",
    "class/lib/context/context.js~Context.html#instance-member-source",
    "lib/context/context.js~Context#source",
    "member"
  ],
  [
    "lib/context/context.js~context#sourcemap",
    "class/lib/context/context.js~Context.html#instance-member-sourceMap",
    "lib/context/context.js~Context#sourceMap",
    "member"
  ],
  [
    "lib/context/context.js~context#sourcepath",
    "class/lib/context/context.js~Context.html#instance-member-sourcePath",
    "lib/context/context.js~Context#sourcePath",
    "member"
  ],
  [
    "lib/context/context.js~context.getinstructions",
    "class/lib/context/context.js~Context.html#static-method-getInstructions",
    "lib/context/context.js~Context.getInstructions",
    "method"
  ],
  [
    "lib/context/context.js~context.getprogramcountermapping",
    "class/lib/context/context.js~Context.html#static-method-getProgramCounterMapping",
    "lib/context/context.js~Context.getProgramCounterMapping",
    "method"
  ],
  [
    "lib/context/index.js",
    "file/lib/context/index.js.html",
    "lib/context/index.js",
    "file"
  ],
  [
    "lib/context/selectors.js",
    "file/lib/context/selectors.js.html",
    "lib/context/selectors.js",
    "file"
  ],
  [
    "lib/context/set.js",
    "file/lib/context/set.js.html",
    "lib/context/set.js",
    "file"
  ],
  [
    "lib/context/set.js~contextset#add",
    "class/lib/context/set.js~ContextSet.html#instance-method-add",
    "lib/context/set.js~ContextSet#add",
    "method"
  ],
  [
    "lib/context/set.js~contextset#addcontext",
    "class/lib/context/set.js~ContextSet.html#instance-method-addContext",
    "lib/context/set.js~ContextSet#addContext",
    "method"
  ],
  [
    "lib/context/set.js~contextset#addressedcontracts",
    "class/lib/context/set.js~ContextSet.html#instance-method-addressedContracts",
    "lib/context/set.js~ContextSet#addressedContracts",
    "method"
  ],
  [
    "lib/context/set.js~contextset#constructor",
    "class/lib/context/set.js~ContextSet.html#instance-constructor-constructor",
    "lib/context/set.js~ContextSet#constructor",
    "method"
  ],
  [
    "lib/context/set.js~contextset#contextforaddress",
    "class/lib/context/set.js~ContextSet.html#instance-method-contextForAddress",
    "lib/context/set.js~ContextSet#contextForAddress",
    "method"
  ],
  [
    "lib/context/set.js~contextset#contextforbinary",
    "class/lib/context/set.js~ContextSet.html#instance-method-contextForBinary",
    "lib/context/set.js~ContextSet#contextForBinary",
    "method"
  ],
  [
    "lib/context/set.js~contextset#contexts",
    "class/lib/context/set.js~ContextSet.html#instance-member-contexts",
    "lib/context/set.js~ContextSet#contexts",
    "member"
  ],
  [
    "lib/context/set.js~contextset#indexforaddress",
    "class/lib/context/set.js~ContextSet.html#instance-member-indexForAddress",
    "lib/context/set.js~ContextSet#indexForAddress",
    "member"
  ],
  [
    "lib/context/set.js~contextset#indexforbinary",
    "class/lib/context/set.js~ContextSet.html#instance-member-indexForBinary",
    "lib/context/set.js~ContextSet#indexForBinary",
    "member"
  ],
  [
    "lib/context/set.js~contextset#merge",
    "class/lib/context/set.js~ContextSet.html#instance-method-merge",
    "lib/context/set.js~ContextSet#merge",
    "method"
  ],
  [
    "lib/context/set.js~contextset.forcontracts",
    "class/lib/context/set.js~ContextSet.html#static-method-forContracts",
    "lib/context/set.js~ContextSet.forContracts",
    "method"
  ],
  [
    "lib/controller/actions/index.js",
    "file/lib/controller/actions/index.js.html",
    "lib/controller/actions/index.js",
    "file"
  ],
  [
    "lib/controller/sagas.js",
    "file/lib/controller/sagas.js.html",
    "lib/controller/sagas.js",
    "file"
  ],
  [
    "lib/debugger.js",
    "file/lib/debugger.js.html",
    "lib/debugger.js",
    "file"
  ],
  [
    "lib/debugger.js~debugger#_call",
    "class/lib/debugger.js~Debugger.html#instance-member-_call",
    "lib/debugger.js~Debugger#_call",
    "member"
  ],
  [
    "lib/debugger.js~debugger#_contexts",
    "class/lib/debugger.js~Debugger.html#instance-member-_contexts",
    "lib/debugger.js~Debugger#_contexts",
    "member"
  ],
  [
    "lib/debugger.js~debugger#_trace",
    "class/lib/debugger.js~Debugger.html#instance-member-_trace",
    "lib/debugger.js~Debugger#_trace",
    "member"
  ],
  [
    "lib/debugger.js~debugger#connect",
    "class/lib/debugger.js~Debugger.html#instance-method-connect",
    "lib/debugger.js~Debugger#connect",
    "method"
  ],
  [
    "lib/debugger.js~debugger#constructor",
    "class/lib/debugger.js~Debugger.html#instance-constructor-constructor",
    "lib/debugger.js~Debugger#constructor",
    "method"
  ],
  [
    "lib/debugger.js~debugger#initialstate",
    "class/lib/debugger.js~Debugger.html#instance-get-initialState",
    "lib/debugger.js~Debugger#initialState",
    "member"
  ],
  [
    "lib/debugger.js~debugger.fortx",
    "class/lib/debugger.js~Debugger.html#static-method-forTx",
    "lib/debugger.js~Debugger.forTx",
    "method"
  ],
  [
    "lib/debugger.js~debugger.selectors",
    "class/lib/debugger.js~Debugger.html#static-get-selectors",
    "lib/debugger.js~Debugger.selectors",
    "member"
  ],
  [
    "lib/effects.js",
    "file/lib/effects.js.html",
    "lib/effects.js",
    "file"
  ],
  [
    "lib/evm/actions/index.js",
    "file/lib/evm/actions/index.js.html",
    "lib/evm/actions/index.js",
    "file"
  ],
  [
    "lib/evm/reducers.js",
    "file/lib/evm/reducers.js.html",
    "lib/evm/reducers.js",
    "file"
  ],
  [
    "lib/evm/sagas.js",
    "file/lib/evm/sagas.js.html",
    "lib/evm/sagas.js",
    "file"
  ],
  [
    "lib/evm/selectors.js",
    "file/lib/evm/selectors.js.html",
    "lib/evm/selectors.js",
    "file"
  ],
  [
    "lib/reducers.js",
    "file/lib/reducers.js.html",
    "lib/reducers.js",
    "file"
  ],
  [
    "lib/sagas.js",
    "file/lib/sagas.js.html",
    "lib/sagas.js",
    "file"
  ],
  [
    "lib/session.js",
    "file/lib/session.js.html",
    "lib/session.js",
    "file"
  ],
  [
    "lib/session.js~session#_store",
    "class/lib/session.js~Session.html#instance-member-_store",
    "lib/session.js~Session#_store",
    "member"
  ],
  [
    "lib/session.js~session#advance",
    "class/lib/session.js~Session.html#instance-method-advance",
    "lib/session.js~Session#advance",
    "method"
  ],
  [
    "lib/session.js~session#constructor",
    "class/lib/session.js~Session.html#instance-constructor-constructor",
    "lib/session.js~Session#constructor",
    "method"
  ],
  [
    "lib/session.js~session#dispatch",
    "class/lib/session.js~Session.html#instance-method-dispatch",
    "lib/session.js~Session#dispatch",
    "method"
  ],
  [
    "lib/session.js~session#failed",
    "class/lib/session.js~Session.html#instance-get-failed",
    "lib/session.js~Session#failed",
    "member"
  ],
  [
    "lib/session.js~session#finished",
    "class/lib/session.js~Session.html#instance-get-finished",
    "lib/session.js~Session#finished",
    "member"
  ],
  [
    "lib/session.js~session#interrupt",
    "class/lib/session.js~Session.html#instance-method-interrupt",
    "lib/session.js~Session#interrupt",
    "method"
  ],
  [
    "lib/session.js~session#state",
    "class/lib/session.js~Session.html#instance-get-state",
    "lib/session.js~Session#state",
    "member"
  ],
  [
    "lib/session.js~session#stepinto",
    "class/lib/session.js~Session.html#instance-method-stepInto",
    "lib/session.js~Session#stepInto",
    "method"
  ],
  [
    "lib/session.js~session#stepnext",
    "class/lib/session.js~Session.html#instance-method-stepNext",
    "lib/session.js~Session#stepNext",
    "method"
  ],
  [
    "lib/session.js~session#stepout",
    "class/lib/session.js~Session.html#instance-method-stepOut",
    "lib/session.js~Session#stepOut",
    "method"
  ],
  [
    "lib/session.js~session#stepover",
    "class/lib/session.js~Session.html#instance-method-stepOver",
    "lib/session.js~Session#stepOver",
    "method"
  ],
  [
    "lib/session.js~session#view",
    "class/lib/session.js~Session.html#instance-method-view",
    "lib/session.js~Session#view",
    "method"
  ],
  [
    "lib/solidity/actions/index.js",
    "file/lib/solidity/actions/index.js.html",
    "lib/solidity/actions/index.js",
    "file"
  ],
  [
    "lib/solidity/reducers.js",
    "file/lib/solidity/reducers.js.html",
    "lib/solidity/reducers.js",
    "file"
  ],
  [
    "lib/solidity/sagas.js",
    "file/lib/solidity/sagas.js.html",
    "lib/solidity/sagas.js",
    "file"
  ],
  [
    "lib/solidity/selectors.js",
    "file/lib/solidity/selectors.js.html",
    "lib/solidity/selectors.js",
    "file"
  ],
  [
    "lib/trace/actions/index.js",
    "file/lib/trace/actions/index.js.html",
    "lib/trace/actions/index.js",
    "file"
  ],
  [
    "lib/trace/reducers.js",
    "file/lib/trace/reducers.js.html",
    "lib/trace/reducers.js",
    "file"
  ],
  [
    "lib/trace/sagas.js",
    "file/lib/trace/sagas.js.html",
    "lib/trace/sagas.js",
    "file"
  ],
  [
    "lib/trace/selectors.js",
    "file/lib/trace/selectors.js.html",
    "lib/trace/selectors.js",
    "file"
  ],
  [
    "lib/types/contract.js",
    "file/lib/types/contract.js.html",
    "lib/types/contract.js",
    "file"
  ],
  [
    "lib/types/contract.js~contract#binary",
    "class/lib/types/contract.js~Contract.html#instance-member-binary",
    "lib/types/contract.js~Contract#binary",
    "member"
  ],
  [
    "lib/types/contract.js~contract#constructor",
    "class/lib/types/contract.js~Contract.html#instance-constructor-constructor",
    "lib/types/contract.js~Contract#constructor",
    "method"
  ],
  [
    "lib/types/contract.js~contract#contractname",
    "class/lib/types/contract.js~Contract.html#instance-member-contractName",
    "lib/types/contract.js~Contract#contractName",
    "member"
  ],
  [
    "lib/types/contract.js~contract#deployedbinary",
    "class/lib/types/contract.js~Contract.html#instance-member-deployedBinary",
    "lib/types/contract.js~Contract#deployedBinary",
    "member"
  ],
  [
    "lib/types/contract.js~contract#deployedsourcemap",
    "class/lib/types/contract.js~Contract.html#instance-member-deployedSourceMap",
    "lib/types/contract.js~Contract#deployedSourceMap",
    "member"
  ],
  [
    "lib/types/contract.js~contract#source",
    "class/lib/types/contract.js~Contract.html#instance-member-source",
    "lib/types/contract.js~Contract#source",
    "member"
  ],
  [
    "lib/types/contract.js~contract#sourcemap",
    "class/lib/types/contract.js~Contract.html#instance-member-sourceMap",
    "lib/types/contract.js~Contract#sourceMap",
    "member"
  ],
  [
    "lib/types/contract.js~contract#sourcepath",
    "class/lib/types/contract.js~Contract.html#instance-member-sourcePath",
    "lib/types/contract.js~Contract#sourcePath",
    "member"
  ],
  [
    "lib/types/index.js",
    "file/lib/types/index.js.html",
    "lib/types/index.js",
    "file"
  ],
  [
    "lib/web3/index.js",
    "file/lib/web3/index.js.html",
    "lib/web3/index.js",
    "file"
  ],
  [
    "lib/web3/index.js~web3adapter#constructor",
    "class/lib/web3/index.js~Web3Adapter.html#instance-constructor-constructor",
    "lib/web3/index.js~Web3Adapter#constructor",
    "method"
  ],
  [
    "lib/web3/index.js~web3adapter#gathercontexts",
    "class/lib/web3/index.js~Web3Adapter.html#instance-method-gatherContexts",
    "lib/web3/index.js~Web3Adapter#gatherContexts",
    "method"
  ],
  [
    "lib/web3/index.js~web3adapter#getdeployedcode",
    "class/lib/web3/index.js~Web3Adapter.html#instance-method-getDeployedCode",
    "lib/web3/index.js~Web3Adapter#getDeployedCode",
    "method"
  ],
  [
    "lib/web3/index.js~web3adapter#gettrace",
    "class/lib/web3/index.js~Web3Adapter.html#instance-method-getTrace",
    "lib/web3/index.js~Web3Adapter#getTrace",
    "method"
  ],
  [
    "lib/web3/index.js~web3adapter#gettransactioninfo",
    "class/lib/web3/index.js~Web3Adapter.html#instance-method-getTransactionInfo",
    "lib/web3/index.js~Web3Adapter#getTransactionInfo",
    "method"
  ],
  [
    "lib/web3/index.js~web3adapter#web3",
    "class/lib/web3/index.js~Web3Adapter.html#instance-member-web3",
    "lib/web3/index.js~Web3Adapter#web3",
    "member"
  ]
]